#!/usr/bin/env sh

code=$1
output=$2
id=$(git rev-parse HEAD)
message=$(git log -1 --pretty=%B )
author=$(git --no-pager show -s --format='%an <%ae>' "$id")
branch=$(git symbolic-ref --short HEAD)

payload=$(echo "{\"channel\":\"#continous3\",\"attachments\":[{\"fallback\":\"Test Failure\",\"text\":\"\",\"fields\":[{\"title\":\"Branch\",\"value\":\"$branch\",\"short\":true},{\"title\":\"Author\",\"value\":\"$author\",\"short\":true},{\"title\":\"Commit\",\"value\":\"$id\",\"short\":true},{\"title\":\"Message\",\"value\":\"$message\",\"short\":true},{\"title\":\"Status\",\"value\":\"FAILED! Push again for staging\",\"short\":true}],\"color\":\"#F35A00\"}]}")

curl -X POST -H 'Content-type: application/json' \
     --data "$payload" https://hooks.slack.com/services/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

clean=$(printf "$output")
curl -F content="$clean" -F channels=\#continous3 -F token=xoxp-38785405123-38785405315-38835058832-521416a579 https://slack.com/api/files.upload
